apiVersion: v1
kind: Namespace
metadata:
  name: tester
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-tester
  namespace: tester
  labels:
    app: experiment-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: experiment-tester
  template:
    metadata:
      labels:
        app: experiment-tester
    spec:
      containers:
        - name: experiment-tester
          image: magneticio/experiment-tester:0.0.3
          env:
            - name: URL_LANDING_PAGE
              value: "http://eshop1-deluxe-jp.democluster.net"
            - name: URL_TARGET_PAGE
              value: "http://eshop1-deluxe-jp.democluster.net"
            - name: NUMBER_OF_AGENTS
              value: "100"