apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-app1
  name: deployment-new2
  namespace: eu-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app1
      version: 1.6.2
  template:
    metadata:
      labels:
        app: demo-app1
        version: 1.6.2
    spec:
      containers:
        - env:
            - name: SHOP_VERSION
              value: "2"
          image: avalcepina/testservice:1.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 9090
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          name: deployment2-0
          ports:
            - containerPort: 9090
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 600Mi
            requests:
              cpu: 400m
              memory: 100Mi