apiVersion: v1
kind: Namespace
metadata:
  name: kubist-demo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-app
    deployment: deployment2
    version: version2
  name: deployment2
  namespace: kubist-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      deployment: deployment2
      version: version2
  template:
    metadata:
      labels:
        app: demo-app
        deployment: deployment2
        version: version2
    spec:
      containers:
      - env:
        - name: SHOP_VERSION
          value: "2"
        - name: GET_FEEDBACK
          value: "no"
        - name: RAILS_RELATIVE_URL_ROOT
          value: "/v2"
        image: magneticio/simpleservice:2.0.14
        imagePullPolicy: IfNotPresent
        name: deployment2-0
        ports:
        - containerPort: 9191
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
