apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-app
  name: deployment2
  namespace: kubist-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      deployment: deployment2
  template:
    metadata:
      labels:
        app: demo-app
        deployment: deployment2
    spec:
      containers:
      - env:
        - name: SHOP_VERSION
          value: "3"
        - name: GET_FEEDBACK
          value: "no"
        - name: VAMP_ELASTICSEARCH_URL
          value: "http://es-service:9200"
        - name: FAILURE
          value: "0.5"
        image: magneticio/simpleservice:2.0.12
        imagePullPolicy: IfNotPresent
        name: deployment2-0
        ports:
        - containerPort: 9191
          protocol: TCP