apiVersion: v1
kind: Namespace
metadata:
  name: kubist-demo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-app
  name: deployment1
  namespace: kubist-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      deployment: deployment1
  template:
    metadata:
      labels:
        app: demo-app
        deployment: deployment1
    spec:
      containers:
      - env:
        - name: SHOP_VERSION
          value: "1"
        - name: GET_FEEDBACK
          value: "no"
        - name: VAMP_ELASTICSEARCH_URL
          value: "http://es-service:9200"
        image: magneticio/simpleservice:2.0.2
        imagePullPolicy: IfNotPresent
        name: deployment1-0
        ports:
        - containerPort: 9191
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-app
  name: deployment2
  namespace: kubist-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      deployment: deployment2
  template:
    metadata:
      labels:
        app: demo-app
        deployment: deployment2
    spec:
      containers:
      - env:
        - name: SHOP_VERSION
          value: "2"
        - name: GET_FEEDBACK
          value: "no"
        - name: VAMP_ELASTICSEARCH_URL
          value: "http://es-service:9200"
        image: magneticio/simpleservice:2.0.2
        imagePullPolicy: IfNotPresent
        name: deployment2-0
        ports:
        - containerPort: 9191
          protocol: TCP
