imagePullSecret: []
labels: {}
metadata: {}
pod:
  containers:
    - environmentVariables:
        GET_FEEDBACK: "no"
        SHOP_VERSION: "1"
        VAMP_ELASTICSEARCH_URL: http://es-service:9200
      healthChecks: []
      image: magneticio/simpleservice:2.0.12
      metadata: {}
      ports:
        - containerPort: 9191
          hostPort: 0
      readyChecks: []
  metadata: {}
policies: []
replicas: 1
selectors:
  deployment: deployment1
policyExecutor:
  name: OptimizedDeploymentPolicyExecutor
  parameters:
    optimizer-config:
      MIN_CPU: 400
      MAX_CPU: 1000
      MIN_MEMORY: 10000000
      MAX_MEMORY: 200000000000
      OBSERVATION_MINUTES: 2
      INITIAL_POINTS: 3