apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    vamp-managed: enabled
    cluster: cluster1
    project: project1
  name: kubist-test1
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app1
  name: deployment1
  namespace: kubist-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      deployment: deployment1
  template:
    metadata:
      labels:
        app: app1
        deployment: deployment1
    spec:
      containers:
      - env:
        - name: SHOP_VERSION
          value: "1"
        - name: GET_FEEDBACK
          value: "no"
        - name: VAMP_ELASTICSEARCH_URL
          value: "http://es-service:9200"
        image: magneticio/simpleservice:2.0.12
        imagePullPolicy: IfNotPresent
        name: deployment1-0
        ports:
        - containerPort: 9191
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app1
  name: deployment2
  namespace: kubist-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      deployment: deployment2
  template:
    metadata:
      labels:
        app: app1
        deployment: deployment2
    spec:
      containers:
      - env:
        - name: SHOP_VERSION
          value: "2"
        - name: GET_FEEDBACK
          value: "no"
        - name: VAMP_ELASTICSEARCH_URL
          value: "http://es-service:9200"
        image: magneticio/simpleservice:2.0.12
        imagePullPolicy: IfNotPresent
        name: deployment1-0
        ports:
        - containerPort: 9191
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app1
  name: deployment3
  namespace: kubist-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      deployment: deployment3
  template:
    metadata:
      labels:
        app: app1
        deployment: deployment3
    spec:
      containers:
      - env:
        - name: SHOP_VERSION
          value: "1"
        - name: GET_FEEDBACK
          value: "no"
        - name: VAMP_ELASTICSEARCH_URL
          value: "http://es-service:9200"
        image: magneticio/simpleservice:2.0.12
        imagePullPolicy: IfNotPresent
        name: deployment1-0
        ports:
        - containerPort: 9191
          protocol: TCP
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    vamp-managed: enabled
  name: kubist-test2
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app2
  name: deployment1
  namespace: kubist-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      deployment: deployment1
  template:
    metadata:
      labels:
        app: app2
        deployment: deployment1
    spec:
      containers:
      - env:
        - name: SHOP_VERSION
          value: "1"
        - name: GET_FEEDBACK
          value: "no"
        - name: VAMP_ELASTICSEARCH_URL
          value: "http://es-service:9200"
        image: magneticio/simpleservice:2.0.12
        imagePullPolicy: IfNotPresent
        name: deployment1-0
        ports:
        - containerPort: 9191
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app2
  name: deployment2
  namespace: kubist-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      deployment: deployment2
  template:
    metadata:
      labels:
        app: app2
        deployment: deployment2
    spec:
      containers:
      - env:
        - name: SHOP_VERSION
          value: "1"
        - name: GET_FEEDBACK
          value: "no"
        - name: VAMP_ELASTICSEARCH_URL
          value: "http://es-service:9200"
        image: magneticio/simpleservice:2.0.12
        imagePullPolicy: IfNotPresent
        name: deployment1-0
        ports:
        - containerPort: 9191
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app2
  name: deployment3
  namespace: kubist-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      deployment: deployment3
  template:
    metadata:
      labels:
        app: app2
        deployment: deployment3
    spec:
      containers:
      - env:
        - name: SHOP_VERSION
          value: "1"
        - name: GET_FEEDBACK
          value: "no"
        - name: VAMP_ELASTICSEARCH_URL
          value: "http://es-service:9200"
        image: magneticio/simpleservice:2.0.12
        imagePullPolicy: IfNotPresent
        name: deployment1-0
        ports:
        - containerPort: 9191
          protocol: TCP
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    vamp-managed: enabled
  name: kubist-test3
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app3
  name: deployment1
  namespace: kubist-test3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
      deployment: deployment1
  template:
    metadata:
      labels:
        app: app3
        deployment: deployment1
    spec:
      containers:
      - env:
        - name: SHOP_VERSION
          value: "1"
        - name: GET_FEEDBACK
          value: "no"
        - name: VAMP_ELASTICSEARCH_URL
          value: "http://es-service:9200"
        image: magneticio/simpleservice:2.0.12
        imagePullPolicy: IfNotPresent
        name: deployment1-0
        ports:
        - containerPort: 9191
          protocol: TCP
